/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.kinokiru.java;

public class App {
    public void getGreeting(int amount) {
        String[] pins = new String[amount * (amount + 1) / 2];

        System.out.println("game start!");
        print(amount, pins, true);

        for (int i = 0; i <= 2; i++) {
            System.out.println("Game " + i);
            for (int j = 0; j < pins.length; j++) {
                if (Math.random() < 0.3) {
                    pins[j] = "X";
                }
            }
            print(amount, pins, false);
        }
    }

    public void print(int amount, String[] pins, boolean fill) {
        for (int i = 0; i < amount; i++) {
            System.out.print(" ".repeat(i));

            for (int j = amount; j > i; j--) {
                if (fill) {
                    pins[j] = "O";
                }
                System.out.print(pins[j]);
            }

            System.out.print('\n');
        }
    }

    public static void main(String[] args) {
        new App().getGreeting(4);
    }
}
